### ISSUE TITLE
Jekyll integration

### ISSUE THREAD

**Issue by btzr-io** [butterthemes/butterthemes#15]

**Comment by streger** [comment]
What's the point with this, to generate this website?

**Comment by btzr-io** [comment]
@streger  `web-app` -> Allow users to install / publish themes.

**Comment by btzr-io** [comment]
So the idea is to make butter use a custom protocol `butter-themes://`

**Comment by btzr-io** [comment]
@streger But this is just a prototype so you can ignore this for now ^^

**Comment by btzr-io** [comment]
https://github.com/allizad/jekyll-webpack

**Comment by btzr-io** [comment]
https://github.com/butterthemes/butterthemes.github.io/issues/18
